# Generated by Django 5.2.7 on 2026-02-26 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_varations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='varations',
            new_name='variations',
        ),
    ]
