# Generated by Django 5.2.7 on 2026-03-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation_delete_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_name',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=200),
        ),
    ]
