# Generated by Django 5.2.7 on 2026-04-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_variation_variation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_name',
            field=models.CharField(choices=[('size', 'size'), ('color', 'color')], max_length=200),
        ),
    ]
