# Generated by Django 5.2.7 on 2026-02-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('store', '0004_variation_delete_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
